"""add chat_messages table

Revision ID: e944e308b13b
Revises: 3840f3c7a13b
Create Date: 2025-10-16 20:59:58.284430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e944e308b13b'
down_revision: Union[str, Sequence[str], None] = '3840f3c7a13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id_fk', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id_fk'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_memory', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chat_memory_chat_id'), 'chat_memory', ['chat_id'], unique=True)
    op.drop_column('chat_memory', 'persona')
    op.drop_column('chat_memory', 'flags')
    op.drop_column('chat_memory', 'last_summary_at')
    op.drop_column('chat_memory', 'updated_at')
    op.add_column('chats', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('chats', sa.Column('summary', sa.Text(), nullable=True))
    op.alter_column('chats', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=True)
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    op.drop_column('chats', 'chat_type')
    op.drop_column('chats', 'title')
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'username')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'name')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'id')
    op.add_column('chats', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('chat_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.alter_column('chats', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.drop_column('chats', 'summary')
    op.drop_column('chats', 'id')
    op.add_column('chat_memory', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('chat_memory', sa.Column('last_summary_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('chat_memory', sa.Column('flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('chat_memory', sa.Column('persona', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_chat_memory_chat_id'), table_name='chat_memory')
    op.drop_column('chat_memory', 'id')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
